// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wytoahovazxbzojugzmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5dG9haG92YXp4YnpvanVnem13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NzU0ODcsImV4cCI6MjA3NTQ1MTQ4N30.6RRKGGwsJqsQuiCVJnXf7D8OS2Li7nyNRS52Pm0UC94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});